name: Infrastructure workflow

on:
  push:
    branches: [main]
    paths: ['infrastructure/**']
  pull_request:
    paths: ['infrastructure/**']
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write # per oidc

jobs:
  plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v6

      - name: AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: eu-south-1

      - name: OpenTofu setup
        uses: opentofu/setup-opentofu@v1

      - name: tofu init
        run: tofu init
        working-directory: infrastructure/opentofu

      - name: tofu plan
        run: tofu plan -out=tfplan 2>&1 | tee plan.txt
        working-directory: infrastructure/opentofu

      - name: Plan as comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('infrastructure/opentofu/plan.txt', 'utf8');
            const truncated = plan.length > 60000 ? plan.slice(0, 60000) + '\n...(truncated)' : plan;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### OpenTofu Plan\n\`\`\`\n${truncated}\n\`\`\``
            });


  apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: eu-south-1

      - name: Opentofu setup
        uses: opentofu/setup-opentofu@v1

      - name: Kubectl setup
        uses: azure/setup-kubectl@v4

      - name: Tell working directory
        run: |
          pwd
          ls -la
        working-directory: infrastructure/opentofu

      - name: tofu init
        run: tofu init
        working-directory: infrastructure/opentofu

      - name: tofu apply
        run: tofu apply -auto-approve
        working-directory: infrastructure/opentofu

      # loop smart per aspettare il kubeconfig
      - name: Attendi kubeconfig su SSM
        run: |
          echo "Attendo che il control plane completi l'inizializzazione..."
          MAX_ATTEMPTS=40        # 40 tentativi
          SLEEP_SECONDS=30       # ogni 30 secondi = max 20 minuti
          
          for i in $(seq 1 $MAX_ATTEMPTS); do
            echo "Tentativo $i/$MAX_ATTEMPTS..."
            
            if aws ssm get-parameter \
              --name "/k8s/kubeconfig" \
              --with-decryption \
              --region ${{ vars.AWS_REGION }} > /dev/null 2>&1; then
              echo "Kubeconfig disponibile!"
              exit 0
            fi
            
            echo "Non ancora disponibile, riprovo tra ${SLEEP_SECONDS}s..."
            sleep $SLEEP_SECONDS
          done
          
          echo "Timeout — il control plane non ha completato l'inizializzazione"
          exit 1


      - name: Get kubeconfig
        run: |
          aws ssm get-parameter \
            --name "/k8s/kubeconfig" \
            --with-decryption \
            --query Parameter.Value \
            --output text > kubeconfig
          chmod 600 kubeconfig

      - name: Set postgres db password as k8s secret
        run: KUBECONFIG=./kubeconfig create secret generic postgres-secret --from-literal=password=${{ secrets.POSTGRE_SECRET }} \
            --dry-run=client -o yaml | KUBECONFIG=./kubeconfig kubectl apply -f -